%YAML 1.1
---
name: Local Config
version: 1.0.0
schema: v1
model_defaults: &model_defaults
  provider: ollama
  apiBase: http://localhost:11434/

models:
  - name: Autodetect
    <<: *model_defaults
    model: AUTODETECT
  - name: qwen2.5-coder-7b
    <<: *model_defaults
    model: qwen2.5-coder:7b
    roles:
      - autocomplete
  - name: qwen3-reranker-8b
    <<: *model_defaults
    model: hf.co/mradermacher/Qwen3-Reranker-8B-GGUF:Q4_K_M
    roles:
      - rerank